version: '3.9'

services:
  db:
    image: mongo
    container_name: test-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234
    networks:
      - app-network
  
  db-client:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin1234
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin1234@db:27017/
    depends_on:
      - db
    networks:
      - app-network
        
  app:
    hostname: app
    container_name: golang-clean-template
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - 8080:8080 
    restart: always
    volumes:
      -  ./:/app
    depends_on: 
      - db
    env_file:
      - .env
    networks:
      - app-network

volumes:
  app_vol:

networks:
  app-network:
    driver: bridge
