package dto

const (
	MESSAGE_FAILED_PROSES_REQUEST  = "認証が失敗しました"
	MESSAGE_FAILED_TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND"
	MESSAGE_FAILED_TOKEN_NOT_VALID = "TOKEN_NOT_FOUND"
	MESSAGE_FAILED_DENIED_ACCESS   = "DENIED_ACCESS"
)
